In [4]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np

In [6]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [7]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(a[0])

[1 2 3 4]


In [10]:
print(a[1])

[5 6 7 8]


In [11]:
a = np.array([1,2,3])

In [12]:
print(a)

[1 2 3]


In [13]:
a

array([1, 2, 3])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.empty(5)

array([1.21140688e-311, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [17]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [29]:
arr = np.array([1,2,3,4,5,6])

In [30]:
np.append(arr,[0,7,9])

array([1, 2, 3, 4, 5, 6, 0, 7, 9])

In [32]:
np.delete(arr,2)

array([1, 2, 4, 5, 6])

In [33]:
arr = np.array([9,12,31,4,54,36])

In [34]:
np.sort(arr)

array([ 4,  9, 12, 31, 36, 54])

In [36]:
ndarray.ndim(arr)

NameError: name 'ndarray' is not defined

In [37]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [38]:
array_example.ndim

3

In [39]:
array_example.size

24

In [40]:
array_example.shape

(3, 2, 4)

In [51]:
arr_satu = np.array([[1,2,3,4,5,6]])

In [52]:
arr_satu.ndim

2

In [53]:
arr_satu.size

6

In [54]:
arr_satu.shape

(1, 6)

In [55]:
arr_dua = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])

In [56]:
arr_dua.ndim

2

In [57]:
arr_dua.size

12

In [58]:
arr_dua.shape

(2, 6)

In [65]:
a = np.arange(6)

In [66]:
a

array([0, 1, 2, 3, 4, 5])

In [67]:
b = a.reshape(2,3)

In [68]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
b = a.reshape(3,2)

In [71]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [75]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [76]:
a.shape

(6,)

In [79]:
a2 = a[np.newaxis]
print(a2)

[[1 2 3 4 5 6]]


In [80]:
print(a2.shape)

(1, 6)


In [83]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [84]:
b = np.expand_dims(a,axis = 1)

In [85]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [86]:
b.shape

(6, 1)

In [87]:
c = np.expand_dims(a,axis = 0)

In [88]:
c
c.shape

(1, 6)

In [99]:
x = np.full((4,3),(1,10,1))
print(x)

[[ 1 10  1]
 [ 1 10  1]
 [ 1 10  1]
 [ 1 10  1]]


In [96]:
x[0,1]

25

In [100]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [101]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
a[1,2]

7

In [104]:
five_up = (a>5)

In [106]:
print(a[five_up])

[ 6  7  8  9 10 11 12]


In [107]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [108]:
kelipatan_2 = a[a%2==0]

In [109]:
print(kelipatan_2ipatan_2)

NameError: name 'kelipatan_2ipatan_2' is not defined

In [110]:
print(kelipatan_2)

[ 2  4  6  8 10 12]


In [112]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr1 = arr[0:4]

In [115]:
arr1

array([1, 2, 3, 4])